server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: git
  rabbitmq:
    host: 172.30.1.13
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/Work/native-file-repo
        git: #default
          uri: file:///C:/Users/swkan/Documents/LG CNS Bootcamp/spring-config-git
#          uri: https://github.com/joneconsulting/spring-cloud-config
          default-label: master
#          username: [username]
#          password: [password]
#        encrypt:
#          enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - httpexchanges
          - busrefresh